### ISSUE TITLE
naming of subject directories

### ISSUE THREAD

**Issue by tbweng** [HBClab/xnat_downloader#1]
It would be nice to have the option of supplying a dictionary for naming subjects differently than they are labeled on xnat. I think the depracated xnat_BIDS would reference an external .csv file for subject naming (e.g., sub-GEA161)

**Comment by jdkent** [comment]
I didn't document it in the README (sorry), but this functionality [still exists](https://github.com/HBClab/xnat_downloader/blob/master/xnat_downloader/cli/run.py#L190), and is documented (briefly) in the [documentation](http://xnat-downloader.readthedocs.io/en/latest/JSON.html)

> subject_variables_csv: A path/file.csv designation where the entries in the first column are the participant labels (not zeropadded), and each subsequent column is a variable you wish to append to the subject label such as group membership (Exp or Con) or some condition (GE or SE).

If using that option doesn't work, let me know, and I will work on a fix.
